# Generated by Django 4.1.6 on 2024-04-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=10),
            preserve_default=False,
        ),
    ]
