# Generated by Django 4.1.6 on 2023-02-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_status',
            field=models.BooleanField(default=True),
        ),
    ]
