# Generated by Django 4.1.6 on 2023-02-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_billing_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
