# Generated by Django 4.1.6 on 2023-08-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
