# Generated by Django 4.1.6 on 2024-04-09 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_total_value'),
        ('orders', '0006_inventoryreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryreport',
            old_name='quantity_sold',
            new_name='amount_sold',
        ),
        migrations.AddField(
            model_name='inventoryreport',
            name='inventory_on_hand',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventoryreport',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
