# Generated by Django 4.1.6 on 2024-05-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_creditorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditorder',
            name='no_items_left',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
