# Generated by Django 4.1.6 on 2023-02-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_billing_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_status',
            field=models.BooleanField(default=False),
        ),
    ]
