# Generated by Django 4.1.6 on 2024-05-27 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_creditorder_no_items_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryreport',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='inventoryreport',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='creditOrder',
        ),
    ]
