# Generated by Django 4.1.6 on 2024-05-27 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_inventoryreport_created_inventoryreport_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryreport',
            name='updated',
        ),
    ]
