# Generated by Django 4.1.6 on 2024-05-27 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_remove_inventoryreport_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryreport',
            old_name='amount_sold',
            new_name='quantity_sold',
        ),
    ]
