# Generated by Django 4.1.6 on 2024-05-29 07:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_rename_amount_sold_inventoryreport_quantity_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryreport',
            name='last_inventory_change',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
