# Generated by Django 4.1.6 on 2024-05-29 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_inventoryreport_last_inventory_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryreport',
            name='last_inventory_change',
        ),
    ]
