# Generated by Django 4.1.6 on 2024-05-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_order_part_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='balance_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
