# Generated by Django 4.1.6 on 2024-05-29 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_order_balance_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='balance_paid',
        ),
    ]
