# Generated by Django 4.1.6 on 2024-06-02 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_salesreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreport',
            name='created',
        ),
        migrations.AddField(
            model_name='salesreport',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_reports', to='orders.order'),
        ),
    ]
