# Generated by Django 4.1.6 on 2024-06-02 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_remove_salesreport_created_salesreport_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreport',
            name='report_end_date',
        ),
        migrations.RemoveField(
            model_name='salesreport',
            name='report_start_date',
        ),
    ]
