# Generated by Django 4.1.6 on 2024-06-02 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_remove_salesreport_report_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreport',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
