# Generated by Django 4.1.6 on 2024-06-03 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_remove_salesreport_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreport',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_reports', to='orders.order'),
        ),
    ]
