# Generated by Django 4.1.6 on 2024-06-03 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_salesreport_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreport',
            name='order',
        ),
    ]
