# Generated by Django 4.1.6 on 2024-06-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_salesreport_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreport',
            name='order',
        ),
        migrations.AddField(
            model_name='salesreport',
            name='order',
            field=models.ManyToManyField(null=True, related_name='sales_reports', to='orders.order'),
        ),
    ]
