# Generated by Django 4.1.6 on 2024-06-07 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_product_title'),
        ('orders', '0040_salesreport_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreport',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
