# Generated by Django 4.1.6 on 2024-06-08 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0044_salesreport_product_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreport',
            name='product_title',
        ),
    ]
