# Generated by Django 4.1.6 on 2024-06-24 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0045_remove_salesreport_product_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreport',
            name='product_price',
        ),
    ]
